#!/usr/bin/env bash
set -euo pipefail

# Net2Sheet Backend Setup Script
# This script helps you set up the environment and generate a unique bucket name

echo "🔧 Net2Sheet Backend Setup"
echo "=========================="

# Check if .env already exists
if [ -f ".env" ]; then
  echo "⚠️  .env file already exists!"
  read -p "Do you want to overwrite it? (y/N): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Setup cancelled. Existing .env file preserved."
    exit 0
  fi
fi

# Copy example.env to .env
cp example.env .env
echo "✅ Created .env file from example.env"

# Generate unique bucket name
TIMESTAMP=$(date +%s)
UNIQUE_BUCKET="net2sheet-uploads-${TIMESTAMP}"

# Get current gcloud project (if available)
DEFAULT_PROJECT=$(gcloud config get-value project 2>/dev/null || echo "")

# Interactive configuration
echo ""
echo "📝 Please provide the following information:"
echo ""

# Project ID
if [ -n "$DEFAULT_PROJECT" ]; then
  read -p "Google Cloud Project ID [$DEFAULT_PROJECT]: " PROJECT_ID
  PROJECT_ID=${PROJECT_ID:-$DEFAULT_PROJECT}
else
  read -p "Google Cloud Project ID: " PROJECT_ID
fi

# Region
read -p "Region [us-central1]: " REGION
REGION=${REGION:-us-central1}

# Bucket name
read -p "Storage Bucket Name [$UNIQUE_BUCKET]: " BUCKET
BUCKET=${BUCKET:-$UNIQUE_BUCKET}

# Sheet ID
echo ""
echo "📊 For Google Sheets integration, you need to provide the Sheet ID."
echo "   Example: https://docs.google.com/spreadsheets/d/SHEET_ID_HERE/edit"
echo "   The SHEET_ID is the long string in the URL."
echo ""
read -p "Google Sheet ID: " SHEET_ID

# Sheet range
read -p "Sheet Range [Sheet1!A1]: " SHEET_RANGE
SHEET_RANGE=${SHEET_RANGE:-Sheet1!A1}

# JWT Secret
echo ""
echo "🔐 Generating JWT secret..."
JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "PLEASE-CHANGE-THIS-TO-A-RANDOM-STRING-$(date +%s)")

# Update .env file
cat > .env << EOF
# Net2Sheet Backend Environment Variables
# Generated by setup.sh on $(date)

# Google Cloud Project Configuration
PROJECT_ID=${PROJECT_ID}
REGION=${REGION}

# Cloud Storage
BUCKET=${BUCKET}

# Cloud Run Service Configuration
SERVICE_NAME=net2sheet-upload
JOB_NAME=csv-to-sheets-job

# Google Sheets Configuration
SHEET_ID=${SHEET_ID}
SHEET_RANGE=${SHEET_RANGE}

# JWT Authentication
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=1h

# CORS Configuration (for Chrome Extension)
ALLOWED_ORIGINS=chrome-extension://*

# Development/Local Testing
PORT=8080
EOF

echo ""
echo "✅ Configuration complete! Your .env file has been created with:"
echo "   Project ID: ${PROJECT_ID}"
echo "   Region: ${REGION}"
echo "   Bucket: ${BUCKET}"
echo "   Sheet ID: ${SHEET_ID}"
echo "   Sheet Range: ${SHEET_RANGE}"
echo ""
echo "🚀 Next steps:"
echo "   1. Review and edit .env if needed"
echo "   2. Run: ./deploy.sh"
echo "   3. After deployment, share your Google Sheet with the service account"
echo ""
echo "💡 Tip: Keep your .env file secure and never commit it to version control!"
